# Generated by Django 4.2 on 2023-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='hyper',
            field=models.CharField(default='href', max_length=255),
            preserve_default=False,
        ),
    ]
