# Generated by Django 4.2 on 2023-05-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='yt_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
